# Generated by Django 2.1 on 2018-09-19 05:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the Category', max_length=200)),
                ('description', models.TextField(help_text='Enter the brief description of the Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the Item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Enter the brief description of the Item', null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for each action', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, help_text='Enter the date of the action', null=True)),
                ('price', models.FloatField(default=0, help_text='Enter the price of the item')),
                ('quantity', models.BigIntegerField(default=0, help_text='Enter the number of item')),
                ('status', models.CharField(blank=True, choices=[('i', 'Input'), ('o', 'Output')], default='o', max_length=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.Item')),
            ],
        ),
    ]
