# Generated by Django 2.1 on 2018-10-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20180922_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemaction',
            options={'ordering': ['-date']},
        ),
    ]
